rubyonrailsproject/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  
  resources :images
  resources :posts
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace 'api' do
    namespace 'v1' do
      post 'auth_user' => 'authentication#authenticate_user'
    end
  end


end

rubyonrailsproject/app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :picture, PictureUploader
    
end

rubyonrailsproject/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

rubyonrailsproject/app/controllers/api/v1/api_application_controller.rb
module Api
    module V1
        class ApiApplicationController < ActionController::Base
            
            attr_reader :current_user

            protected
            def authenticate_request!
                unless user_id_in_token?
                    render json: { errors: ['Not Authenticated'] }, status: :unauthorized
                    return
                end
                @current_user = User.find(auth_token[:user_id])
                rescue JWT::VerificationError, JWT::DecodeError
                render json: { errors: ['Not Authenticated'] }, status: :unauthorized
            end

            private
            def http_token
                @http_token ||= if request.headers['Authorization'].present?
                	  request.headers['Authorization'].split(' ').last
                end
            end

            def auth_token
                @auth_token ||= JsonWebToken.decode(http_token)
            end

            def user_id_in_token?
                http_token && auth_token && auth_token[:user_id].to_i
            end

        end
    end
end

rubyonrailsproject/app/controllers/api/v1/authentication_controller.rb
module Api
    module V1
      class AuthenticationController < ApiApplicationController

        def authenticate_user
            if User.find_for_database_authentication(email: params[:email]).present?
                user = User.find_for_database_authentication(email: params[:email])
                if user.valid_password?(params[:password])
                    render json: payload(user)
                else
                    render json: {errors: ['Password invalido' ]}, status: :unauthorized
                end
            else
                render json: {errors: ['Usuario invalido']}, status: :unauthorized
            end
        end

        private
        def payload(user)
        return nil unless user and user.id
            {
                auth_token: JsonWebToken.encode({user_id: user.id}),
                user: {id: user.id, email: user.email, name: user.name}
            }
        end


      end
    end
end

rubyonrailsproject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_devise_params, if: :devise_controller?
  
  def configure_devise_params
      devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end 
end

rubyonrailsproject/app/controllers/images_controller.rb
class ImagesController < ApplicationController

    before_action :set_image, only: [:show, :edit, :update, :destroy]

    def index
        @images = Image.all            # variable de tipo array @images
    end


    def new 
        @image = Image.new
    end

    def create
        #render plain: params[:image].inspect
        @image = Image.new images_params
        @image.save

        #redirect_to @image  #redirecciona a una nueva vista
    end

    def show
        
    end

    def edit
        
    end

    def update
         # buscamos nuestro id del objeto imagen
        @image.update images_params 
        redirect_to @image
    end

    def destroy
        
        @image.destroy
        redirect_to images_path 
    end


    

    private
    
    def images_params
        params.require(:image).permit :description, :picture
    end
    
    def set_image
        @image = Image.find params[:id]
    end
   
    

        

end

rubyonrailsproject/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :author, :publication_date, :?-no-test-framework)
    end
end

rubyonrailsproject/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  
end

rubyonrailsproject/app/helpers/images_helper.rb
module ImagesHelper
end

rubyonrailsproject/app/views/images/_form.html.erb
<div class="form-group"> 
    <%= form_for @image, :html => {:multipart => true} do |f| %>
        <%= f.label 'Descripción' %> <br>
        <%= f.text_field :description, class: 'form-control' %>
        <br>
        <%= f.label 'Cargar Imagen ' %> <br>
        <%= f.file_field :picture, class: 'form-control-file' %>
        <br>
        <%= f.submit 'Enviar', :class => 'btn btn-primary' %>
    <% end %>
</div>



rubyonrailsproject/app/views/images/_image.html.erb
<div class="col">
    <figure class="figure">
        <%= image_tag image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>
        <figcaption class="figure-caption">
            <%= image.description %> 
            <%= link_to 'Editar', edit_image_path(image) %>
            <%= link_to 'Eliminar', image, method: :delete, data:{ 
                    confirm: 'Está seguro que desea eliminar esta imagen.'
                } %>        
        </figcaption> 
    </figure>
</div>

rubyonrailsproject/app/views/images/edit.html.erb
<p>EDITAR IMAGENES</p>
<%= render 'form' %>

rubyonrailsproject/app/views/images/index.html.erb
<div class="row">
    <%= render @images %>
</div>

rubyonrailsproject/app/views/images/new.html.erb
<p>CREAR IMAGENES</p>
<%= render 'form' %>

rubyonrailsproject/app/views/images/show.html.erb
<%= image_tag @image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>

rubyonrailsproject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubyonrailsproject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="nav justify-content-end ig-header-menu">
          <li class="nav-item ig-item-menu">
          <%- if user_signed_in? %> <%# validamos si hay usuario registrado%>
              <li class="nav-item ig-item-menu">
                  <%= link_to 'Salir', destroy_user_session_path, method: :delete %>
              </li>
          <% else %> <%# si no lo esta mostramos los botones de inicio y registro%>
              <li class="nav-item ig-item-menu">
                    <%= link_to 'Iniciar Sesión', new_user_session_path %>
              </li>
              <li class="nav-item ig-item-menu">
                    <%= link_to 'Registrar', new_user_registration_path %>
              </li>
          <% end %>
    </ul>
    <div class="container">
      <div class="ig-alert">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-dismissable" role="alert">
          <button type="button" data-dismiss="alert" class="close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= value %>
        </div>
      <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

rubyonrailsproject/app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :publication_date %>
    <%= f.datetime_select :publication_date %>
  </div>

  <div class="field">
    <%= f.label :?-no-test-framework %>
    <%= f.text_field :?-no-test-framework %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rubyonrailsproject/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Author</th>
      <th>Publication date</th>
      <th>?-no-test-framework</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.author %></td>
        <td><%= post.publication_date %></td>
        <td><%= post.?-no-test-framework %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

rubyonrailsproject/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>

<p>
  <strong>Publication date:</strong>
  <%= @post.publication_date %>
</p>

<p>
  <strong>?-no-test-framework:</strong>
  <%= @post.?-no-test-framework %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

rubyonrailsproject/app/views/welcome/index.html.erb
<h1>ImageGram</h1>
<% if user_signed_in? %>
    <h3>Bienvenido! <%= current_user.email %> </h3>
<% else %>
    <p> por favor inicia sesión para ver imagenes </p>
<% end %>